// This file contains placeholder data that will be used to test and debug initial development versions of CourtHUB

const users = [
  {
    name: 'Lonnie Perot',
    username: 'Lonnie Perot',
    email: 'user@courthub.com',
    password: '123456',
    complete_card: 'true',
  },
  {
    name: 'Alexander Marigold',
    username: 'Alexander Marigold',
    email: 'marigold@courthub.com',
    password: '123456',
    complete_card: 'false',
  },
  {
    name: 'Test User',
    username: 'Test User',
    email: 'test1@courthub.com',
    password: '123456',
  },
  {
    name: 'Test Beginner',
    username: 'Test Beginner',
    email: 'testbeginner@courthub.com',
    password: '123456',
  },
];

const cards = [
  {
    username: 'Lonnie Perot',
    about_player:
      "Been playing tennis since the sweet age of 17. I've got a fat lefty forehand and I love to get around it! Excited to meet some players at Poplar!",
    self_level: 'advanced-intermediate',
    years_xp: 5,
    singles_play: 'true',
    doubles_play: 'true',
    open_play: 'true',
    light_hitting: 'true',
    training_drills: 'true',
    tourn_level: 4.0,
    home_court: 'poplar',
    will_travel: 'true',
    weather_cold: 'true',
    weather_windy: 'true',
    weekday_early_am: 'true',
    weekday_late_am: 'true',
    weekday_early_pm: 'true',
    weekday_late_pm: 'true',
    weekday_evening: 'false',
    weekend_early_am: 'true',
    weekend_late_am: 'true',
    weekend_early_pm: 'true',
    weekend_late_pm: 'true',
    weekend_evening: 'false',
  },
  {
    username: 'Alexander Marigold',
    about_player:
      "I'm the villain of your court!  I love to grunt and be irritable at any distraction on a public tennis court",
    self_level: 'intermediate',
    years_xp: 10,
    singles_play: 'true',
    doubles_play: 'false',
    open_play: 'false',
    light_hitting: 'false',
    training_drills: 'true',
    tourn_level: 3.5,
    home_court: 'fairmount',
    will_travel: 'false',
    weekday_early_am: 'true',
    weekday_late_am: 'true',
    weekday_early_pm: 'true',
    weekday_late_pm: 'true',
    weekday_evening: 'false',
    weekend_early_am: 'true',
    weekend_late_am: 'true',
    weekend_early_pm: 'true',
    weekend_late_pm: 'true',
    weekend_evening: 'false',
  },
  {
    username: 'Test User',
    about_player:
      "test user for debugging registration process, i haven't completed my player profile cause i'm not good at apps",
    self_level: 'advanced',
    years_xp: 20,
    singles_play: 'true',
    doubles_play: 'true',
    open_play: 'false',
    light_hitting: 'false',
    training_drills: 'false',
    tourn_level: 4.5,
    home_court: 'fdr',
    will_travel: 'true',
    weekday_early_am: 'true',
    weekday_late_am: 'true',
    weekday_early_pm: 'true',
    weekday_late_pm: 'true',
    weekday_evening: 'false',
    weekend_early_am: 'true',
    weekend_late_am: 'true',
    weekend_early_pm: 'true',
    weekend_late_pm: 'true',
    weekend_evening: 'false',
  },

  {
    username: 'Test Beginner',
    about_player:
      "test user, i'm a beginner tennis player looking to meet training buddies!",
    self_level: 'beginner',
    years_xp: 0,
    singles_play: 'false',
    doubles_play: 'true',
    open_play: 'true',
    light_hitting: 'true',
    training_drills: 'false',
    tourn_level: 3.0,
    home_court: 'poplar',
    will_travel: 'false',
    weather_cold: 'true',
    weather_windy: 'true',
    weekday_early_am: 'true',
    weekday_late_am: 'true',
    weekday_early_pm: 'true',
    weekday_late_pm: 'true',
    weekday_evening: 'false',
    weekend_early_am: 'true',
    weekend_late_am: 'true',
    weekend_early_pm: 'true',
    weekend_late_pm: 'true',
    weekend_evening: 'false',
  },
];
const conversations = [
  {
    id: 'conv1',
    user1: 'Lonnie Perot',
    user2: 'Alexander Marigold',
    start_time: new Date('2023-12-01T10:00:00Z'),
  },
  {
    id: 'conv2',
    user1: 'Test User',
    user2: 'Test Beginner',
    start_time: new Date('2023-12-02T14:00:00Z'),
  },
];

const messages = [
  {
    id: 'msg1',
    conversation_id: 'conv1',
    sender: 'Lonnie Perot',
    content: 'Hey Alexander, let’s play a match this weekend!',
    timestamp: new Date('2023-12-01T10:15:00Z'),
  },
  {
    id: 'msg2',
    conversation_id: 'conv1',
    sender: 'Alexander Marigold',
    content: 'I’m free on Saturday afternoon. Let’s do it!',
    timestamp: new Date('2023-12-01T10:20:00Z'),
  },
  {
    id: 'msg3',
    conversation_id: 'conv2',
    sender: 'Test User',
    content: 'Hey, looking for someone to practice with. Interested?',
    timestamp: new Date('2023-12-02T14:05:00Z'),
  },
  {
    id: 'msg4',
    conversation_id: 'conv2',
    sender: 'Test Beginner',
    content: 'Sure! Im available on Sunday morning.',
    timestamp: new Date('2023-12-02T14:10:00Z'),
  },
];

module.exports = {
  users,
  cards,
};
